const ASTNodeType = {
  PROGRAM: "PROGRAM",
  VARIABLE_DECLARATION: "VARIABLE_DECLARATION",
  FUNCTION_DECLARATION: "FUNCTION_DECLARATION",
  FUNCTION_CALL: "FUNCTION_CALL",
  ASSIGNMENT: "ASSIGNMENT",
  BINARY_EXPRESSION: "BINARY_EXPRESSION",
  IDENTIFIER: "IDENTIFIER",
  LITERAL: "LITERAL",
  BLOCK: "BLOCK",
  IF_STATEMENT: "IF_STATEMENT",
  WHILE_STATEMENT: "WHILE_STATEMENT",
  FOR_STATEMENT: "FOR_STATEMENT",
  RETURN_STATEMENT: "RETURN_STATEMENT",
};

module.exports = ASTNodeType;
